repositories:
  # aws-infrastructure helm repository
  #
  # When developing charts that will later be merged, it can be helpful to instead point at a branch:
  # url: 'https://raw.githubusercontent.com/<account>/aws-infrastructure/<branch>/helm_repo/'
  - name: 'aws-infrastructure'
    url: 'https://raw.githubusercontent.com/fogies/aws-infrastructure/main/helm_repo/'

  - name: 'couchdb'
    url: 'https://apache.github.io/couchdb-helm'

releases:
  # ingress-crd contains CRDs required by cert-manager and by ingress
  - name: 'ingress-crd'
    namespace: 'ingress-crd'
    chart: 'aws-infrastructure/ingress-crd'
    version: '0.5.0'

  # cert-manager
  - name: 'cert-manager'
    namespace: 'cert-manager'
    chart: 'aws-infrastructure/cert-manager'
    version: '1.6.1'
    needs:
      - 'ingress-crd'

  # ingress
  - name: 'ingress'
    namespace: 'ingress'
    chart: 'aws-infrastructure/ingress'
    version: '0.6.0'
    needs:
      - 'ingress-crd'
    # values:
    #   - # To enable DEBUG logging for Traefik
    #     traefik:
    #       logs:
    #         general:
    #           level: 'DEBUG'

  # CouchDB instance
  - name: 'migraine-database'
    namespace: 'migraine'
    chart: 'couchdb/couchdb'
    version: '3.3.4'
    values:
      - './values/secrets_couchdb_generated.values.yaml'
        # adminUsername: 'XXXXXXXXXX'
        # adminPassword: 'XXXXXXXXXX'
        # cookieAuthSecret: 'XXXXXXXXXX'
        # couchdbConfig:
        #   couchdb:
        #     uuid: 'XXXXXXXXXX'
      - clusterSize: 3
        image:
          repository: 'couchdb'
          tag: '3.2.0'
          pullPolicy: 'Always'
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

  # migraine-celery
  # Installed from a local chart, managed in helmfile-config.yaml
  - name: 'migraine-celery'
    namespace: 'migraine'
    chart: './charts/migraine-celery.tgz'
    values:
      - './values/ecr_generated.values.yaml'

  # migraine-flask
  # Installed from a local chart, managed in helmfile-config.yaml
  - name: 'migraine-flask'
    namespace: 'migraine'
    chart: './charts/migraine-flask.tgz'
    values:
      - './values/ecr_generated.values.yaml'
      - imageName: 'aws_infrastructure_migraine/migraine_flask'
        imageTag: 'latest'

  # migraine-ingress
  # Installed from a local chart, managed in helmfile-config.yaml
  - name: 'migraine-ingress'
    namespace: 'migraine'
    chart: './charts/migraine-ingress.tgz'
    needs:
      - 'ingress'
    values:
      - serviceFlask: 'migraine-flask'

helmDefaults:
  # Prefer explicit management of CRDs via releases
  args:
    - '--skip-crds'

# Prefer explicit errors
missingFileHandler: 'Error'

