apiVersion: 'v1'
kind: 'Service'
metadata:
  name: '{{ .Release.Name }}-flask-prod-service'

spec:
  selector:
    app: '{{ .Release.Name }}-flask'
  ports:
    - port: 8000
      targetPort: 4000
      protocol: 'TCP'
